# Generated by Django 3.0.5 on 2020-05-05 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('deadline', models.DateTimeField()),
                ('cost', models.FloatField()),
                ('img', models.ImageField(upload_to='images')),
                ('des', models.TextField()),
                ('status', models.BooleanField(default=False)),
                ('discipline', models.CharField(choices=[('BE', 'Business Entrepreneurship'), ('CH', 'Chemistry'), ('CT', 'Computer/Info. Technology'), ('ED', 'Engineering/Design'), ('F', 'Food/Agriculture'), ('LS', 'Life Sciences'), ('MS', 'Math/Statistics'), ('PS', 'Physical Sciences'), ('RP', 'Requests for Partners'), ('SI', 'Social Innovation')], default='BE', max_length=2)),
                ('type', models.CharField(choices=[('I', 'Ideation'), ('T', 'Theoritical'), ('R', 'RTP'), ('E', 'eRFP')], default='I', max_length=1)),
                ('pavilions', models.CharField(choices=[('EN', 'Enel'), ('CD', 'COVID-19'), ('AZ', 'AstraZeneca'), ('CC', 'Cleverland Clinic'), ('CT', 'CTTSO'), ('DP', 'DARPA'), ('EL', 'Elanco'), ('HW', 'HIF WASH'), ('LM', 'Lumina'), ('NS', 'NASA'), ('RC', 'Royal Society of Chemistry'), ('TE', 'Tec Edge (Air Force)'), ('UC', 'USSOCOM'), ('UI', 'US Intelligence Community'), ('WT', 'Water'), ('CL', 'Clean Tech'), ('DC', 'Developing Countries'), ('EV', 'Environment'), ('GH', 'Global Health'), ('PG', 'Public Good')], default='EN', max_length=2)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
