# Generated by Django 3.0.5 on 2020-05-05 07:12

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='discipline',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('BE', 'Business Entrepreneurship'), ('CH', 'Chemistry'), ('CT', 'Computer/Info. Technology'), ('ED', 'Engineering/Design'), ('F', 'Food/Agriculture'), ('LS', 'Life Sciences'), ('MS', 'Math/Statistics'), ('PS', 'Physical Sciences'), ('RP', 'Requests for Partners'), ('SI', 'Social Innovation')], max_length=28),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='pavilions',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('EN', 'Enel'), ('CD', 'COVID-19'), ('AZ', 'AstraZeneca'), ('CC', 'Cleverland Clinic'), ('CT', 'CTTSO'), ('DP', 'DARPA'), ('EL', 'Elanco'), ('HW', 'HIF WASH'), ('LM', 'Lumina'), ('NS', 'NASA'), ('RC', 'Royal Society of Chemistry'), ('TE', 'Tec Edge (Air Force)'), ('UC', 'USSOCOM'), ('UI', 'US Intelligence Community'), ('WT', 'Water'), ('CL', 'Clean Tech'), ('DC', 'Developing Countries'), ('EV', 'Environment'), ('GH', 'Global Health'), ('PG', 'Public Good')], max_length=59),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('I', 'Ideation'), ('T', 'Theoritical'), ('R', 'RTP'), ('E', 'eRFP')], max_length=7),
        ),
    ]
