# Generated by Django 3.0.5 on 2020-05-05 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200505_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='user',
        ),
    ]
